#ifndef MSP430_STDIO_REWRITE
#define MSP430_STDIO_REWRITE


#warning "重定向stdio到UART 开关 'MSP430_ENABLE_UART_PRINTF' 'MSP430_ENABLE_UART_SCANF'"
#define MSP430_ENABLE_UART_PRINTF 1
#define MSP430_ENABLE_UART_SCANF 0


#endif //MSP430_STDIO_REWRITE
